/*
 * Aspose.Diagram Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.diagram.model;

import java.util.Objects;
import com.aspose.cloud.diagram.model.PageData;
import com.aspose.cloud.diagram.model.SaaSposeResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiResponseOfListOfPageData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-17T15:16:20.992+08:00")
public class ApiResponseOfListOfPageData extends SaaSposeResponse {
  @SerializedName("Model")
  private List<PageData> model = null;

  public ApiResponseOfListOfPageData model(List<PageData> model) {
    this.model = model;
    return this;
  }

  public ApiResponseOfListOfPageData addModelItem(PageData modelItem) {
    if (this.model == null) {
      this.model = new ArrayList<PageData>();
    }
    this.model.add(modelItem);
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @ApiModelProperty(value = "")
  public List<PageData> getModel() {
    return model;
  }

  public void setModel(List<PageData> model) {
    this.model = model;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiResponseOfListOfPageData apiResponseOfListOfPageData = (ApiResponseOfListOfPageData) o;
    return Objects.equals(this.model, apiResponseOfListOfPageData.model) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(model, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiResponseOfListOfPageData {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

