/*
 * Aspose.Diagram Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.diagram.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * page setting info
 */
@ApiModel(description = "page setting info")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-17T15:16:20.992+08:00")
public class PageSetting {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("NameU")
  private String nameU = null;

  @SerializedName("PageWidth")
  private Double pageWidth = null;

  @SerializedName("PageHeight")
  private Double pageHeight = null;

  public PageSetting name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Page Name
   * @return name
  **/
  @ApiModelProperty(value = "Page Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PageSetting nameU(String nameU) {
    this.nameU = nameU;
    return this;
  }

   /**
   * Page Name
   * @return nameU
  **/
  @ApiModelProperty(value = "Page Name")
  public String getNameU() {
    return nameU;
  }

  public void setNameU(String nameU) {
    this.nameU = nameU;
  }

  public PageSetting pageWidth(Double pageWidth) {
    this.pageWidth = pageWidth;
    return this;
  }

   /**
   * Page Width
   * @return pageWidth
  **/
  @ApiModelProperty(value = "Page Width")
  public Double getPageWidth() {
    return pageWidth;
  }

  public void setPageWidth(Double pageWidth) {
    this.pageWidth = pageWidth;
  }

  public PageSetting pageHeight(Double pageHeight) {
    this.pageHeight = pageHeight;
    return this;
  }

   /**
   * Page Height
   * @return pageHeight
  **/
  @ApiModelProperty(value = "Page Height")
  public Double getPageHeight() {
    return pageHeight;
  }

  public void setPageHeight(Double pageHeight) {
    this.pageHeight = pageHeight;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageSetting pageSetting = (PageSetting) o;
    return Objects.equals(this.name, pageSetting.name) &&
        Objects.equals(this.nameU, pageSetting.nameU) &&
        Objects.equals(this.pageWidth, pageSetting.pageWidth) &&
        Objects.equals(this.pageHeight, pageSetting.pageHeight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, nameU, pageWidth, pageHeight);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageSetting {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameU: ").append(toIndentedString(nameU)).append("\n");
    sb.append("    pageWidth: ").append(toIndentedString(pageWidth)).append("\n");
    sb.append("    pageHeight: ").append(toIndentedString(pageHeight)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

