/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.diagram.model;

import java.util.Objects;
import com.aspose.cloud.diagram.model.SharpModel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PageModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-10-29T11:18:23.179+08:00")
public class PageModel {
  @SerializedName("PageName")
  private String pageName = null;

  @SerializedName("Sharps")
  private List<SharpModel> sharps = null;

  public PageModel pageName(String pageName) {
    this.pageName = pageName;
    return this;
  }

   /**
   * Get pageName
   * @return pageName
  **/
  @ApiModelProperty(value = "")
  public String getPageName() {
    return pageName;
  }

  public void setPageName(String pageName) {
    this.pageName = pageName;
  }

  public PageModel sharps(List<SharpModel> sharps) {
    this.sharps = sharps;
    return this;
  }

  public PageModel addSharpsItem(SharpModel sharpsItem) {
    if (this.sharps == null) {
      this.sharps = new ArrayList<SharpModel>();
    }
    this.sharps.add(sharpsItem);
    return this;
  }

   /**
   * Get sharps
   * @return sharps
  **/
  @ApiModelProperty(value = "")
  public List<SharpModel> getSharps() {
    return sharps;
  }

  public void setSharps(List<SharpModel> sharps) {
    this.sharps = sharps;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageModel pageModel = (PageModel) o;
    return Objects.equals(this.pageName, pageModel.pageName) &&
        Objects.equals(this.sharps, pageModel.sharps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageName, sharps);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageModel {\n");
    
    sb.append("    pageName: ").append(toIndentedString(pageName)).append("\n");
    sb.append("    sharps: ").append(toIndentedString(sharps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

