/*
 * Aspose.Diagram Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.diagram.model;

import java.util.Objects;
import com.aspose.cloud.diagram.model.DrawShapeData;
import com.aspose.cloud.diagram.model.PointF;
import com.aspose.cloud.diagram.model.ShapeStyleData;
import com.aspose.cloud.diagram.model.TextStyleData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PolylineData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-17T15:16:20.992+08:00")
public class PolylineData extends DrawShapeData {
  @SerializedName("Points")
  private List<PointF> points = null;

  public PolylineData points(List<PointF> points) {
    this.points = points;
    return this;
  }

  public PolylineData addPointsItem(PointF pointsItem) {
    if (this.points == null) {
      this.points = new ArrayList<PointF>();
    }
    this.points.add(pointsItem);
    return this;
  }

   /**
   * Get points
   * @return points
  **/
  @ApiModelProperty(value = "")
  public List<PointF> getPoints() {
    return points;
  }

  public void setPoints(List<PointF> points) {
    this.points = points;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolylineData polylineData = (PolylineData) o;
    return Objects.equals(this.points, polylineData.points) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(points, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolylineData {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

