/*
 * Aspose.Diagram Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.diagram.model;

import java.util.Objects;
import com.aspose.cloud.diagram.model.SaaSposeResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SaveAsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-09-23T16:24:55.850+08:00")
public class SaveAsResponse extends SaaSposeResponse {
  @SerializedName("SourceFile")
  private String sourceFile = null;

  @SerializedName("SavedFile")
  private String savedFile = null;

  @SerializedName("Additionals")
  private List<String> additionals = null;

  public SaveAsResponse sourceFile(String sourceFile) {
    this.sourceFile = sourceFile;
    return this;
  }

   /**
   * Get sourceFile
   * @return sourceFile
  **/
  @ApiModelProperty(value = "")
  public String getSourceFile() {
    return sourceFile;
  }

  public void setSourceFile(String sourceFile) {
    this.sourceFile = sourceFile;
  }

  public SaveAsResponse savedFile(String savedFile) {
    this.savedFile = savedFile;
    return this;
  }

   /**
   * Get savedFile
   * @return savedFile
  **/
  @ApiModelProperty(value = "")
  public String getSavedFile() {
    return savedFile;
  }

  public void setSavedFile(String savedFile) {
    this.savedFile = savedFile;
  }

  public SaveAsResponse additionals(List<String> additionals) {
    this.additionals = additionals;
    return this;
  }

  public SaveAsResponse addAdditionalsItem(String additionalsItem) {
    if (this.additionals == null) {
      this.additionals = new ArrayList<String>();
    }
    this.additionals.add(additionalsItem);
    return this;
  }

   /**
   * Get additionals
   * @return additionals
  **/
  @ApiModelProperty(value = "")
  public List<String> getAdditionals() {
    return additionals;
  }

  public void setAdditionals(List<String> additionals) {
    this.additionals = additionals;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaveAsResponse saveAsResponse = (SaveAsResponse) o;
    return Objects.equals(this.sourceFile, saveAsResponse.sourceFile) &&
        Objects.equals(this.savedFile, saveAsResponse.savedFile) &&
        Objects.equals(this.additionals, saveAsResponse.additionals) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceFile, savedFile, additionals, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaveAsResponse {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    sourceFile: ").append(toIndentedString(sourceFile)).append("\n");
    sb.append("    savedFile: ").append(toIndentedString(savedFile)).append("\n");
    sb.append("    additionals: ").append(toIndentedString(additionals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

