/*
 * Aspose.Diagram Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.diagram.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ShapeData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-04-17T15:16:20.992+08:00")
public class ShapeData {
  @SerializedName("ID")
  private Long ID = null;

  @SerializedName("PinX")
  private Double pinX = null;

  @SerializedName("PinY")
  private Double pinY = null;

  public ShapeData ID(Long ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getID() {
    return ID;
  }

  public void setID(Long ID) {
    this.ID = ID;
  }

  public ShapeData pinX(Double pinX) {
    this.pinX = pinX;
    return this;
  }

   /**
   * Get pinX
   * @return pinX
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getPinX() {
    return pinX;
  }

  public void setPinX(Double pinX) {
    this.pinX = pinX;
  }

  public ShapeData pinY(Double pinY) {
    this.pinY = pinY;
    return this;
  }

   /**
   * Get pinY
   * @return pinY
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getPinY() {
    return pinY;
  }

  public void setPinY(Double pinY) {
    this.pinY = pinY;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShapeData shapeData = (ShapeData) o;
    return Objects.equals(this.ID, shapeData.ID) &&
        Objects.equals(this.pinX, shapeData.pinX) &&
        Objects.equals(this.pinY, shapeData.pinY);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ID, pinX, pinY);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShapeData {\n");
    
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    pinX: ").append(toIndentedString(pinX)).append("\n");
    sb.append("    pinY: ").append(toIndentedString(pinY)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

