/*
 * Aspose.Diagram Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aspose.cloud.diagram.api;

import java.io.File;

import org.junit.Assert;
import org.junit.Test;

import com.aspose.cloud.diagram.client.ApiException;
import com.aspose.cloud.diagram.model.CreateNewResponse;
import com.aspose.cloud.diagram.model.DiagramSaveOptions;
import com.aspose.cloud.diagram.model.FilesUploadResult;
import com.aspose.cloud.diagram.model.HTMLSaveOptions;
import com.aspose.cloud.diagram.model.ImageSaveOptions;
import com.aspose.cloud.diagram.model.PdfSaveOptions;
import com.aspose.cloud.diagram.model.SVGSaveOptions;
import com.aspose.cloud.diagram.model.SWFSaveOptions;
import com.aspose.cloud.diagram.model.SaveAsResponse;
import com.aspose.cloud.diagram.model.SaveOptionsRequest;
import com.aspose.cloud.diagram.model.XPSSaveOptions;

/**
 * API tests for DiagramApi
 */
public class ConvertTests extends TestBase {

	private DiagramApi diagramApi = GetDiagramApi();
	private StorageApi storageApi = GetStorageApi();

	public ConvertTests() throws ApiException {
		super();
		// TODO Auto-generated constructor stub
		UploadFileTest();
	}

	/// <summary>
	/// Test FileDownloadWithFormat
	/// </summary>
	@Test
	public void DownloadWithFormat() throws ApiException {
		String name = "FileUpload.vdx";
		String folder = GetStorageTestFOLDER();
		File response = diagramApi.downloadFileWithFormat(name, "pdf", folder);
		Assert.assertNotNull(response);
	}

	/// <summary>
	/// Test FileSaveAs
	/// </summary>
	@Test
	public void SaveAs() throws ApiException {
		String name = "FileUpload.vdx";
		SaveOptionsRequest request = new SaveOptionsRequest();
		request.setFileName("FileSaveAs.pdf");
		request.setFolder(GetStorageTestFOLDER());
		SaveAsResponse response = diagramApi.saveAs(name, request, GetStorageTestFOLDER(), true);

		Assert.assertNotNull(response.getSavedFile());
	}

	/// <summary>
	/// Test FileSaveAs
	/// </summary>
	@Test
	public void SaveAsPDF() throws ApiException {
		String name = "FileUpload.vdx";
		SaveOptionsRequest request = new SaveOptionsRequest();
		request.setFileName("FileSaveAs.pdf");
		request.setFolder(GetStorageTestFOLDER());

		PdfSaveOptions saveOptions = new PdfSaveOptions();
		saveOptions.setIsExportComments(true);
		saveOptions.setJpegQuality(100);

		request.setSaveOptions(saveOptions);
		SaveAsResponse response = diagramApi.saveAs(name, request, GetStorageTestFOLDER(), true);
		Assert.assertNotNull(response.getSavedFile());
	}

	/// <summary>
	/// Test FileSaveAs
	/// </summary>
	@Test
	public void SaveAsPNG() throws ApiException {
		String name = "FileUpload.vdx";
		SaveOptionsRequest request = new SaveOptionsRequest();
		request.setFileName("FileSaveAs.png");
		request.setFolder(GetStorageTestFOLDER());

		ImageSaveOptions saveOptions = new ImageSaveOptions();
		saveOptions.setIsExportComments(true);
		saveOptions.setJpegQuality(100);

		request.setSaveOptions(saveOptions);
		SaveAsResponse response = diagramApi.saveAs(name, request, GetStorageTestFOLDER(), true);
		Assert.assertNotNull(response.getSavedFile());
	}

	/// <summary>
	/// Test FileSaveAs
	/// </summary>
	@Test
	public void SaveAsBMP() throws ApiException {
		String name = "FileUpload.vdx";
		SaveOptionsRequest request = new SaveOptionsRequest();
		request.setFileName("FileSaveAs.bmp");
		request.setFolder(GetStorageTestFOLDER());
		ImageSaveOptions saveOptions = new ImageSaveOptions();
		saveOptions.setIsExportComments(true);
		saveOptions.setJpegQuality(100);

		request.setSaveOptions(saveOptions);
		SaveAsResponse response = diagramApi.saveAs(name, request, GetStorageTestFOLDER(), true);
		Assert.assertNotNull(response.getSavedFile());
	}

	/// <summary>
	/// Test FileSaveAs
	/// </summary>
	@Test
	public void SaveAsVSSX() throws ApiException {
		String name = "FileUpload.vdx";
		SaveOptionsRequest request = new SaveOptionsRequest();
		request.setFileName("FileSaveAs.vssx");
		request.setFolder(GetStorageTestFOLDER());
		DiagramSaveOptions saveOptions = new DiagramSaveOptions();
		request.setSaveOptions(saveOptions);

		SaveAsResponse response = diagramApi.saveAs(name, request, GetStorageTestFOLDER(), true);
		Assert.assertNotNull(response.getSavedFile());
	}

	/// <summary>
	/// Test FileSaveAs
	/// </summary>
	@Test
	public void SaveAsVSTM() throws ApiException {
		String name = "FileUpload.vdx";
		SaveOptionsRequest request = new SaveOptionsRequest();
		request.setFileName("FileSaveAs.vstm");
		request.setFolder(GetStorageTestFOLDER());
		DiagramSaveOptions saveOptions = new DiagramSaveOptions();
		request.setSaveOptions(saveOptions);
		SaveAsResponse response = diagramApi.saveAs(name, request, GetStorageTestFOLDER(), true);
		Assert.assertNotNull(response.getSavedFile());
	}

	/// <summary>
	/// Test FileSaveAs
	/// </summary>
	@Test
	public void SaveAsSVG() throws ApiException {
		String name = "FileUpload.vdx";
		SaveOptionsRequest request = new SaveOptionsRequest();
		request.setFileName("FileSaveAs.svg");
		request.setFolder(GetStorageTestFOLDER());
		SVGSaveOptions saveOptions = new SVGSaveOptions();
		saveOptions.setQuality(100);
		request.setSaveOptions(saveOptions);
		SaveAsResponse response = diagramApi.saveAs(name, request, GetStorageTestFOLDER(), true);
		Assert.assertNotNull(response.getSavedFile());
	}

	/// <summary>
	/// Test FileSaveAs
	/// </summary>
	@Test
	public void SaveAsSWF() throws ApiException {
		String name = "FileUpload.vdx";
		SaveOptionsRequest request = new SaveOptionsRequest();
		request.setFileName("FileSaveAs.swf");
		request.setFolder(GetStorageTestFOLDER());
		SWFSaveOptions saveOptions = new SWFSaveOptions();
		saveOptions.setSaveForegroundPagesOnly(true);
		request.setSaveOptions(saveOptions);
		SaveAsResponse response = diagramApi.saveAs(name, request, GetStorageTestFOLDER(), true);
		Assert.assertNotNull(response.getSavedFile());
	}

	/// <summary>
	/// Test FileSaveAs
	/// </summary>
	@Test
	public void SaveAsHTML() throws ApiException {
		String name = "FileUpload.vdx";
		SaveOptionsRequest request = new SaveOptionsRequest();
		request.setFileName("FileSaveAs.html");
		request.setFolder(GetStorageTestFOLDER());
		HTMLSaveOptions saveOptions = new HTMLSaveOptions();
		saveOptions.setTitle("Save HTML Test");
		request.setSaveOptions(saveOptions);
		SaveAsResponse response = diagramApi.saveAs(name, request, GetStorageTestFOLDER(), true);
		Assert.assertNotNull(response.getSavedFile());
		Assert.assertTrue(response.getAdditionals().size() > 0);
	}

	/// <summary>
	/// Test FileSaveAs
	/// </summary>
	@Test
	public void SaveAsXPS() throws ApiException {
		String name = "FileUpload.vdx";
		SaveOptionsRequest request = new SaveOptionsRequest();
		request.setFileName("FileSaveAs.xps");
		request.setFolder(GetStorageTestFOLDER());
		XPSSaveOptions saveOptions = new XPSSaveOptions();
		saveOptions.setSaveForegroundPagesOnly(true);
		request.setSaveOptions(saveOptions);
		SaveAsResponse response = diagramApi.saveAs(name, request, GetStorageTestFOLDER(), true);
		Assert.assertNotNull(response.getSavedFile());
	}

	/// <summary>
	/// Test DiagramFilePutCreate
	/// </summary>
	@Test
	public void CreateTest() throws ApiException {
		String name = "FileCreate.vdx";
		String folder = GetStorageTestFOLDER();
		CreateNewResponse response = diagramApi.createNew(name, folder, true);
		Assert.assertNotNull(response.getCreated());
	}

	/// <summary>
	/// Test DiagramFilePutCreate
	/// </summary>
	@Test
	public void ConvertApiTest() throws ApiException {
		String name = "Convert.pdf";
		File file = new File(GetSourceFolder() + GetLocalTestSourceFile());
		File response = diagramApi.convertDocument(name, file, GetLocalTestSourceFile());
		Assert.assertNotNull(response);
	}

	@Test
	public void UploadFileTest() throws ApiException {
		String name = "FileUpload.vdx";
		String folder = GetStorageTestFOLDER();
		File file = new File(GetSourceFolder() + name);
		FilesUploadResult response = storageApi.uploadFile(folder + "\\" + name, file, null);
		Assert.assertTrue(response.getUploaded().size() > 0);
	}
}
