/*
 * Aspose.Diagram Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aspose.cloud.diagram.api;

import org.junit.Assert;
import org.junit.Test;

import com.aspose.cloud.diagram.client.ApiClient;
import com.aspose.cloud.diagram.client.ApiException;
import com.aspose.cloud.diagram.model.AccessTokenResponse;

/**
 * API tests for OAuthApi
 */
public class OAuthApiTests extends TestBase {

	public OAuthApiTests() throws ApiException {
		super();
		// TODO Auto-generated constructor stub
	}

	private final OAuthApi api = new OAuthApi();

	@Test
	public void oAuthPostTest() throws ApiException {
		ApiClient apiClient = new ApiClient();
		apiClient.setBasePath("https://api.aspose.cloud");
		api.setApiClient(apiClient);
		AccessTokenResponse response = api.oAuthPost(grantType, clientId, clientSecret);
		Assert.assertNotNull(response.getAccessToken());
	}

}
