/*
 * Web API Swagger specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.diagram.api;
import com.aspose.cloud.diagram.client.ApiClient;
import com.aspose.cloud.diagram.client.ApiException;
import com.aspose.cloud.diagram.client.Configuration;


import com.aspose.cloud.diagram.model.AccessTokenResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OAuthApi
 */
@Ignore
public class OAuthApiTest {

    private final OAuthApi api = new OAuthApi();    
	
    
    /**
     * Get Access token
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oAuthPostTest() throws ApiException {
        String grantType = null;
        String clientId = null;
        String clientSecret = null;
        ApiClient apiClient =new ApiClient();
		apiClient.setBasePath("https://api.aspose.cloud/");
		api.setApiClient( apiClient);
        AccessTokenResponse response = api.oAuthPost(grantType, clientId, clientSecret);
        System.out.println(response.getAccessToken());
        // TODO: test validations
    }
    
}
